#!/bin/bash
# CodeSolveAfrica - Quick Start Guide
# This script helps you get started with the application

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     CodeSolveAfrica - Professional UI Website Ready!           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Your application is fully responsive and configured!"
echo ""
echo "📱 RESPONSIVE DESIGN:"
echo "   • Mobile (320px+)    ✓"
echo "   • Tablet (640px+)    ✓"
echo "   • Desktop (1024px+)  ✓"
echo "   • Large (1280px+)    ✓"
echo ""
echo "⚙️  ENVIRONMENT FILES CONFIGURED:"
echo "   • backend/.env       ✓ MongoDB & JWT configured"
echo "   • .env.local         ✓ API URL configured"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 QUICK START (3 STEPS):"
echo ""
echo "  Step 1: Install Dependencies"
echo "  ─────────────────────────────────────"
echo "  $ npm install"
echo ""
echo "  Step 2: Start Backend (in new terminal, from backend/)"
echo "  ─────────────────────────────────────"
echo "  $ cd backend"
echo "  $ npm start"
echo ""
echo "  Step 3: Start Frontend"
echo "  ─────────────────────────────────────"
echo "  $ npm run dev"
echo ""
echo "  Then open: http://localhost:5173"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 DOCUMENTATION AVAILABLE:"
echo ""
echo "  1. FINAL_CHECKLIST.md"
echo "     → Quick overview of what's complete"
echo ""
echo "  2. RESPONSIVE_DESIGN_GUIDE.md"
echo "     → Complete responsive design reference"
echo ""
echo "  3. ENV_DEPLOYMENT_GUIDE.md"
echo "     → Environment setup & deployment options"
echo ""
echo "  4. SETUP_GUIDE.md"
echo "     → Detailed installation instructions"
echo ""
echo "  5. DEPLOYMENT_READY.md"
echo "     → Deployment guide"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 TESTING THE APPLICATION:"
echo ""
echo "  Mobile Testing:"
echo "  • Open DevTools (F12)"
echo "  • Toggle device toolbar (Ctrl+Shift+M)"
echo "  • Test on iPhone (375px)"
echo ""
echo "  Desktop Testing:"
echo "  • Test navigation, forms, and all pages"
echo "  • Verify API connection (try contact form)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚢 BUILDING FOR PRODUCTION:"
echo ""
echo "  $ npm run build"
echo "  $ npm run preview"
echo ""
echo "  Output: dist/ folder ready for deployment"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚡ IMPORTANT BEFORE PRODUCTION:"
echo ""
echo "  1. Update API URLs in .env.local:"
echo "     VITE_API_URL=https://your-production-api.com"
echo ""
echo "  2. Update backend .env:"
echo "     MONGO_URI=your_production_mongodb_uri"
echo "     JWT_SECRET=your_strong_secret_key"
echo ""
echo "  3. Test all forms with backend"
echo "  4. Run npm run build"
echo "  5. Test production build"
echo "  6. Deploy to your server"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❓ NEED HELP?"
echo ""
echo "  • Check RESPONSIVE_DESIGN_GUIDE.md for responsive design"
echo "  • Check ENV_DEPLOYMENT_GUIDE.md for environment setup"
echo "  • Check DEPLOYMENT_READY.md for deployment options"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Ready to get started? Run: npm install"
echo ""
